---
language: generic

services:
  - docker

deploy:
  - provider: script
    script: travis-build.sh
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]{1,2}+\.[0-9]{1,2}+\.[0-9]{1,2}+(-.*)?$
