---
apiVersion: v1
kind: Service
metadata:
  name: tour-ui
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: tour-ui-mapping
      prefix: /
      service: tour-ui
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: tour
    component: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour
      component: ui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tour
        component: ui
    spec:
      containers:
      - name: tour-ui
        image: nkrause/tour:ui-latest
        ports:
        - name: http
          containerPort: 5000
        