---
apiVersion: getambassador.io/v1beta2
kind: FilterPolicy
metadata:
  name: httpbin-policy
spec:
  rules:
    - host: "*"
      path: /auth/*
      public: true
    - host: "*"
      path: /get-quote/*
      public: false
      filters:
        - name: keycloak
